dist: trusty
sudo: required
language: go

go:
  - 1.9.x

env:
  - MYSQL_IMAGE=mysql/mysql-server:5.7

services:
  - docker

go_import_path: github.com/percona/mysqld_exporter

before_script:
  - sudo service mysql stop
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make
  - make test
  - make tarball

notifications:
  email: false

deploy:
  provider: releases
  user: fjpqzm@gmail.com
  password:
    secure: JNd86tvtMGH6rvwQKVWWy84C1KCWLlWKvv26uQmZ52yoF0HVD5X2rHN8rt0CdMlyVSF/Zq8BqMmhEU0goulQY2qG9MvncxNegVDGMJ3cNhGt5Gm/zTBTs6WuLLvBeM6Ib3oriUUDcVvr+M9vNcArZC1/Xt65IK8v6O9FW+2uxoVdNtXc92BejaNxcY+WRjKG/vK29ogCIKuMn/JprJVNn71v/SgzgpGIaQcjUWct0MZTQXOnrfaP93i/E8iJfyJTSayTSuRnQ84vruKEJLSvzW/noqSeNX0SYs8RcyiRGfthFj3iw/SYJGajuFdinP8SG45MlLTNkw91B/RJSk4U8ZOIh9BdisizxeAZJWH4EZ9aZTp/ytxaz6PVDrmHo+lKPMdPF3J6qaDW/HGBtZQ2T1i3VjX1hsCNRZO3zVOgpFo/6Wk3EHRhhS7V7EVudbxBy5umM8w+LV0fcTX2+PcPz1xbjfDGCbEsnHtACsghyTswtsLt/qWanHkWwmNdXEaCctqCb+w0MCM2xqOabNgYU7cPot0PBEmZvIMIVHIAmmiK1fjre1enEuy5bRV+zBFfugoJBLz00wNOfm1ETzI1PsnOF1gm7yQDF14hEymqJksehmyj1AKlSkf1EJqRJj1a7z7dxkriPNE5s+Wvx0iCHmOfwCphxsxtlQZ84tZ+fiY=
  file: mysqld_exporter*.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

