dist: trusty
sudo: required
language: go

go:
  - 1.9.x

env:
  - MYSQL_IMAGE=mysql/mysql-server:5.7

services:
  - docker

go_import_path: github.com/percona/mysqld_exporter

before_script:
  - sudo service mysql stop
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make
  - make test
  - make tarball

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: "Ic9dWf1BJrMTmFNU96vMfaYmLNkKBdqvJ6UlIRWwlLq43YkwInwAhSrSo9Vz6Aj0078hx+ax23ABnOEyf+r+ogHJ0hSvlhHXnJyiFDGKB4355VSX0ZJr+CHZM20WpZYWmzVKL2A0IbaqO7PXI2/KncPT9JxDtAe3AizuGgGEIBnyIQuEqU6sL97wbmaND0qDHbtV04plHI57d5nA5bDMj6D/ztbaZEgngUrBqAhc3h3lpHpRqUdQAsLHuCEkJwhqCVZaGL361qcaf29kbRRJ7QAMnRzF9BF7IX7ZbK92EDRGqn2o5v7MjyU688AdCJE7La9Rtj99/xpqN2zPd8kCVzXnz8Krpy+PIyVR0tyggnSCmamFl+F8WuTK7VAdcGhoUezhQiHxxqdhGTObJzceAdVRAFuv8wTsZg4wubiiG1j4HhzwfAr3GbCk4nC/usU55FzkDT+fi1EFABKfPCdImoDYf/DxhCfkBs9MCzuJmaJO2JLgaqoknJuq2qjZv9QasyWSUAAYRhkAb4Dt+yZnj4fFU1tFUcgZr3q9SHHM+8ZaNu5YEQ6x0aGgZasJzd0NKmhQkktSAVvgcx3V6OfPhc3ooIUqOVJhrWoMd0i64w7//n0i6GIhtL8oIraYHDJNmrzrAIo6ZkfeMI/25N/Ehtv6MADtW0Pqus20zSRsYKU="
  file: mysqld_exporter*.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

